logging:
  level:
    org.springframework: ERROR
    org.zalando.logbook.Logbook: TRACE
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %marker %logger{36} - [%mdc] - %msg%n"
server:
  port: 8081
  servlet:
    encoding:
      charset: "UTF-8"
      force: true
      enabled: true
  tomcat:
    max-http-form-post-size: 50MB
    max-swallow-size: 50MB

spring:
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      mvc:
        routes:
          - id: test-service
            uri: http://localhost:8082
            predicates:
              - Path=/test/**
            filters:
              - TokenRelay=
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            authorization-grant-type: authorization_code
            client-id: test-client
            client-secret: nbtdgUW2uJMCMuwhCgfhOdPFv5Eexjzp
            scope: openid
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: http://localhost:9990/realms/test-realm

springdoc:
  packagesToScan: ru.examples
  swagger-ui:
    tags-sorter: alpha